def call(msg):
    prompt = msg.get("message", "")
    return {
        "reply": f"[SIMULATED REPLY] You said: '{prompt}' — Response generated by {msg.get('from_agent')}",
        "confidence": 0.85,
        "source_model": "local-stub"
    }